find_package(SigCxx REQUIRED MODULE)
find_package(DBusCxx REQUIRED MODULE)

set(CONTRACTS_BASE   "${CMAKE_CURRENT_SOURCE_DIR}/fabric-contracts")
set(INVENTORY_API_BASE "${CMAKE_CURRENT_SOURCE_DIR}/api/include")
set(INVENTORY_CORE_BASE "${CMAKE_CURRENT_SOURCE_DIR}/core/include")
set(LIBS_BASE        "${CMAKE_CURRENT_SOURCE_DIR}/libs")
set(LIBS_CLIENT_BASE "${CMAKE_CURRENT_SOURCE_DIR}/libs/inventory-client")
set(PUBLISHERS_BASE  "${CMAKE_CURRENT_SOURCE_DIR}/publishers")
set(SRC_BASE         "${CMAKE_CURRENT_SOURCE_DIR}/src")

add_subdirectory(core)
add_subdirectory(api)
add_subdirectory(io)
add_subdirectory(publishers)
add_subdirectory(libs)
add_subdirectory(apps)
